### ISSUE TITLE
New question old issue on install error

### ISSUE THREAD

**Issue by GMonte101** [marl/crepe#101]
I'm getting the following error; I know that the setup.py file was re-written by oriyonay to correct this.
How do I target the pip install to correct version of crepe?
My system is Windows 11 and I am using Python 3.12
My apologies, I am relatively new to Python.

![Crepe](https://github.com/marl/crepe/assets/140988098/9f66a336-6f36-4888-bf77-9e78eadc9ecf)

**Comment by chromeatty** [comment]
have the exact issue

**Comment by jongwook** [comment]
Hi, this was fixed in #94 but it appears that 0.0.14 on PyPI somehow didn't include the fix. I just pushed 0.0.15 so it should work now.

**Comment by GMonte101** [comment]
Sorry Sir,

I'm still getting the error
<img width="881" alt="image" src="https://github.com/marl/crepe/assets/140988098/a74a5b32-ed0f-45b6-8158-4aac6dce7ad6">
